package ua.riaval.quiztest.entity;

// Generated 04.11.2013 10:49:58 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AnswerAnswer generated by hbm2java
 */
@Entity
@Table(name = "Answer_Answer", catalog = "QuizTest")
public class AnswerAnswer implements java.io.Serializable {

	private int anAnId;
	private Answer answerByParentAnswerId;
	private Answer answerByChildAnswerId;

	public AnswerAnswer() {
	}

	public AnswerAnswer(int anAnId, Answer answerByParentAnswerId,
			Answer answerByChildAnswerId) {
		this.anAnId = anAnId;
		this.answerByParentAnswerId = answerByParentAnswerId;
		this.answerByChildAnswerId = answerByChildAnswerId;
	}

	@Id
	@Column(name = "an_an_id", unique = true, nullable = false)
	public int getAnAnId() {
		return this.anAnId;
	}

	public void setAnAnId(int anAnId) {
		this.anAnId = anAnId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "parent_answer_id", nullable = false)
	public Answer getAnswerByParentAnswerId() {
		return this.answerByParentAnswerId;
	}

	public void setAnswerByParentAnswerId(Answer answerByParentAnswerId) {
		this.answerByParentAnswerId = answerByParentAnswerId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "child_answer_id", nullable = false)
	public Answer getAnswerByChildAnswerId() {
		return this.answerByChildAnswerId;
	}

	public void setAnswerByChildAnswerId(Answer answerByChildAnswerId) {
		this.answerByChildAnswerId = answerByChildAnswerId;
	}

}
