package ua.riaval.quiztest.entity;

// Generated 04.11.2013 10:49:58 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AnswerResult generated by hbm2java
 */
@Entity
@Table(name = "AnswerResult", catalog = "QuizTest")
public class AnswerResult implements java.io.Serializable {

	private Integer id;
	private QuestionResult questionResult;
	private String text;
	private Boolean correct;
	private boolean checked;

	public AnswerResult() {
	}

	public AnswerResult(QuestionResult questionResult, String text,
			boolean checked) {
		this.questionResult = questionResult;
		this.text = text;
		this.checked = checked;
	}

	public AnswerResult(QuestionResult questionResult, String text,
			Boolean correct, boolean checked) {
		this.questionResult = questionResult;
		this.text = text;
		this.correct = correct;
		this.checked = checked;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "questionResult_id", nullable = false)
	public QuestionResult getQuestionResult() {
		return this.questionResult;
	}

	public void setQuestionResult(QuestionResult questionResult) {
		this.questionResult = questionResult;
	}

	@Column(name = "text", nullable = false, length = 200)
	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	@Column(name = "correct")
	public Boolean getCorrect() {
		return this.correct;
	}

	public void setCorrect(Boolean correct) {
		this.correct = correct;
	}

	@Column(name = "checked", nullable = false)
	public boolean isChecked() {
		return this.checked;
	}

	public void setChecked(boolean checked) {
		this.checked = checked;
	}

}
