package ua.riaval.quiztest.entity;

// Generated 04.11.2013 10:49:58 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.LinkedHashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Quiz generated by hbm2java
 */
@Entity
@Table(name = "Quiz", catalog = "QuizTest")
public class Quiz implements java.io.Serializable {

	private Integer id;
	private String name;
	private String comment;
	private Date timeLimit;
	private int amount;
	private Set<Comment> comments = new LinkedHashSet<Comment>();
	private Set<QuizCategory> quizCategories = new LinkedHashSet<QuizCategory>();
	private Set<Question> questions = new LinkedHashSet<Question>();

	public Quiz() {
	}

	public Quiz(String name, String comment, Date timeLimit, int amount) {
		this.name = name;
		this.comment = comment;
		this.timeLimit = timeLimit;
		this.amount = amount;
	}

	public Quiz(String name, String comment, Date timeLimit, int amount,
			Set<Comment> comments, Set<QuizCategory> quizCategories,
			Set<Question> questions) {
		this.name = name;
		this.comment = comment;
		this.timeLimit = timeLimit;
		this.amount = amount;
		this.comments = comments;
		this.quizCategories = quizCategories;
		this.questions = questions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "comment", nullable = false, length = 500)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "timeLimit", nullable = false, length = 8)
	public Date getTimeLimit() {
		return this.timeLimit;
	}

	public void setTimeLimit(Date timeLimit) {
		this.timeLimit = timeLimit;
	}

	@Column(name = "amount", nullable = false)
	public int getAmount() {
		return this.amount;
	}

	public void setAmount(int amount) {
		this.amount = amount;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "quiz")
	public Set<Comment> getComments() {
		return this.comments;
	}

	public void setComments(Set<Comment> comments) {
		this.comments = comments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "quiz")
	public Set<QuizCategory> getQuizCategories() {
		return this.quizCategories;
	}

	public void setQuizCategories(Set<QuizCategory> quizCategories) {
		this.quizCategories = quizCategories;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "quiz")
	public Set<Question> getQuestions() {
		return this.questions;
	}

	public void setQuestions(Set<Question> questions) {
		this.questions = questions;
	}

}
